pop-os/packaging-thunderbird

- debian/control
- debian/control.in
> fix: package thunderbird-gnome-support

- debian/thunderbird.desktop
> fix: Set StartupWMClass properly for ESR version

- SHA256SUMS
- debian/changelog
> Thunderbird 128.3.2esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.4.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/6c9a5fd8ba8d5956ce0cca04af0bb8f14c4c0f03
> Thunderbird 128.4.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.4.1esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/d67d4ee10f43a317181ab2717f9978a1bd25e6b4
> Thunderbird 128.4.1esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.4.2esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/ffdb226764722cd45544f945ef51e1786e1bdbbe
> Thunderbird 128.4.2esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.4.4esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/e963642f77edeb0a8a39ffdca4c7f2dee69f0b78
> Thunderbird 128.4.4esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.5.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/5aa787475f1ff704f48d561dd2ba209b092f8336
> Thunderbird 128.5.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.5.2esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/2e403316e9cb803e5ad9bd34eab5bf812fd32186
> Thunderbird 128.5.2esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.6.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/ae3d6df4c922bfec881437177690a3115d85b469
> Thunderbird 128.6.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.7.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/a491e151dc3fd5830fec3d4ea0c83b4ecc651a9a
> Thunderbird 128.7.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.7.1esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/165c27a12acb651ed64f594c36ee6369820f722d
> Thunderbird 128.7.1esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.8.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/a9ae94e74147aed62efe452d5ae6c486d5443300
> Thunderbird 128.8.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.8.1esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/6fd564fcb98669b2d718d567ccc072d3d0aaf103
> Thunderbird 128.8.1esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.9.0esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/ac4a25a5a9f043aeece186ccb593f54800b562cc
> Thunderbird 128.9.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.9.1esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/1905cef5b9f0901b8f8b67b8093b0b0dbb92ca06
> Thunderbird 128.9.1esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.9.2esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/3dc116e792891bdcfaaa36232ed71fb2a79ed570
> Thunderbird 128.9.2esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.10.0esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/fb57b123f3f34cc4fdca17761f3743351afee769
> Thunderbird 128.10.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.10.1esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/88d37ec175b0fd667783201820dc364088216fcc
> Thunderbird 128.10.1esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.11.0esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/3abba23fa667473fade7fe4c44e2b8d25dba5fd1
> Thunderbird 128.11.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.13.0esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/5183734297a83650c01416013d872b84cd9c12da
> Thunderbird 128.13.0esr

- SHA256SUMS
- debian/changelog
* https://www.mozilla.org/en-US/thunderbird/128.14.0esr/releasenotes/
* https://hg-edge.mozilla.org/releases/comm-esr128/log/4361681615e70a0c339fd3780f1f383395a9a7df
> Thunderbird 128.14.0esr
